#!/bin/bash

# $Id: genscreenshots,v 1.1 2002/01/03 17:35:06 joern Exp $

FROM=~/tmp
TO=~/projects/dvdrip/htdocs/img
HTML=~/projects/dvdrip/htdocs/index.html

for i in preferences storage rip clipzoom transcode logging
do
	convert $FROM/$i.tiff -quality 75 $TO/$i.jpg
	convert $FROM/$i.tiff -quality 50 -geometry 200x200 $TO/thumb_$i.jpg

	WIDTH=$(identify $TO/$i.jpg | perl -ne 'm/(\d+)x(\d+)/; print $1')
	HEIGHT=$(identify $TO/$i.jpg | perl -ne 'm/(\d+)x(\d+)/; print $2')
	echo "$i.jpg: WIDTH=$WIDTH HEIGHT=$HEIGHT"
	perl -pi -e "s/$i.jpg',\d+,\d+/$i.jpg',$WIDTH,$HEIGHT/" $HTML

	WIDTH=$(identify $TO/thumb_$i.jpg | perl -ne 'm/(\d+)x(\d+)/; print $1')
	HEIGHT=$(identify $TO/thumb_$i.jpg | perl -ne 'm/(\d+)x(\d+)/; print $2')
	echo "thumb_$i.jpg: WIDTH=$WIDTH HEIGHT=$HEIGHT"
	perl -pi -e "s/thumb_$i.jpg.*height=.\d+./thumb_$i.jpg\" width=\"$WIDTH\" height=\"$HEIGHT\"/" $HTML

done
